### ISSUE TITLE
Wrong definitions because of word of the day

### ISSUE THREAD

**Issue by francescoignaziore** [nickcharlton/urbanscraper#108]
Hello! Thanks for building urbanscraper and make it accessible to everyone. I have noticed that whenever we look for a word, when getting the results, we also get the JSON object related to the 'word of the day'. It's particularly deceiving because the word name appear according to the one we looked, but the definition and all the other info are instead the one related to the daily word.

Here an example: a looked for the word 'Karen'. However it's easy to see how the second object does not refer to it. It refers in fact to the term 'vaxhole'.
I am trying to solve the problem and also to add an entry in the json object related to the number of thumbs up. However it's the first time I use ruby so I am struggling a bit. 

![Cattura](https://user-images.githubusercontent.com/35643402/111391598-3e752800-86b5-11eb-9081-c3a05a15a789.PNG)

**Comment by nickcharlton** [comment]
Thanks for opening this issue.

Unfortunately, I'm not looking to spend much more time on UrbanScraper and have been intending for a while to shut it down. I'm going to be archiving this repo, but you're welcome to take things as is and make modifications.
