### ISSUE TITLE
Live version offline

### ISSUE THREAD

**Issue by brycied00d** [nickcharlton/urbanscraper#3]
I'm not sure the best place to report this, but the linked live version at http://urbanscraper.herokuapp.com/  is returning "Application Error." I first noticed this in February but assumed the issue was merely transient; it was running fine back in January.

**Comment by nickcharlton** [comment]
Hi @brycied00d! I hadn't noticed this. I'll take a look at it tomorrow morning and see what's up.

**Comment by nickcharlton** [comment]
To give an update on this: It's failing to start because it's failing to load part of the markdown library it uses for the docs:

```ruby
helpers/markdown.rb:19:in `<top (required)>': uninitialized constant Tilt::Redcarpet2Template::Redcarpet2 (NameError)
```

I've got a decent idea about why this might be the case, so it should be up and running again shortly.

**Comment by nickcharlton** [comment]
This is now fixed.

Thanks for reporting!

**Comment by brycied00d** [comment]
That's great! I'm sorry I didn't bring it up sooner.
